### ISSUE TITLE
use absolute imports

### ISSUE THREAD

**Issue by amaloney** [arviz-devs/arviz-base#19]
In `base.py` module we have relative imports

https://github.com/arviz-devs/arviz-base/blob/9392eb0b7100c6fceb1afd08e49f43be7c5604e7/src/arviz_base/base.py#L14-L16

We should use absolute imports within the repo.

**Comment by OriolAbril** [comment]
We have to change the pre-commit check, I copied it over from current arviz, but I also prefer absolute imports: https://github.com/arviz-devs/arviz-base/blob/main/.pre-commit-config.yaml#L21

**Comment by amaloney** [comment]
Yes, I just ran into that. Fixing now as the absoluify imports has been archived
