### ISSUE TITLE
rcParams updates and changes

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz-base#4]
With the new version, we can change some rcParams, update their defaults and add extra ones. Here is the list of changes so far, we should discuss which changes to keep here before the initial release:

### New rcParams
* data.sample_dims. This is now configurable and it is used both when creating arviz related object and when using them. Defaults to ["chain", "draw"] but can be any list of hashable.
* stats.module. Importable python object to be used for stats related computations. It is general string for now, including the library name, but it could be restricted to submodules within arviz_stats if it is a string, yet allow when using `rcParams["stats.module"] = python.object` to use user defined classes.
* stats.ci_kind. hdi or eti, type of credible interval to be used by default. It didn't exist but everything used hdi. I initially set the default to eti because I implemented it earlier, but I don't really care which becomes the default.
* 

### Modified rcParams
* stats.ci_prob (used to be hdi_prob). I have also changed it to 0.83 for no reason other than keeping people on their toes.
* plot.point_estimate. Might make sense to move to stats.point_estimate and use it for the point estimate in az.summary as default.

### Updated rcParams
* (proposal) data.log_likelihood. It is still set to True but there is an issue at ArviZ to use False (also PyMC is not longer using that value at all). Do we want to change the default? Or get rid of it completely?

---

Note: for now I have also removed a lot of backend specific options related to plotting. I think we should try to keep them to a minimum, but we could keep some of them.

**Comment by aloctavodia** [comment]
should we have default stats.ci_prob value closer to a "standard" value, we use 0.94 in ArviZ because is not 0.95 but close. In statistical rethinking, the default is 0.89, because is close to 0.90. Maybe we could use 0.91?

**Comment by aloctavodia** [comment]
Not sure about eti or hdi...

**Comment by sethaxen** [comment]
90% is also considerably more stable to estimate than 95%, so I'd lean towards something close to 90% as a default. RE eti vs hdi, I slightly lean towards HDI for consistency. I think we're the only package in town that defaults to HDI over ETI though.

**Comment by sethaxen** [comment]
I have a slight preference for an even number. Currently with 94%, we have 3% and 97% in the summary column. With 89 or 91, we have to add a decimal and additional digit, which takes up valuable horizontal space.

**Comment by OriolAbril** [comment]
As there doesn't seem to be very strong opinions on hdi vs eti, I think we can go with eti as it seems to be more stable and robust, and especially when plotting bands, more intuitive (see https://github.com/arviz-devs/arviz/discussions/2021 for example).

For the default probability, would for example 88 or 92 still be close enough to 90 so we get the annoying people by closeness to common value while using even number to minimize use of horizontal space?

For `plot.point_estimate` my proposal is to move it to `stats.point_estimate` and for `stats.module` to enforce it is either a user provided python object o a submodule within arviz_stats to avoid making it exceedingly easy that due to a typo we end up executing code from a malicious library through arviz.

**Comment by aloctavodia** [comment]
Sounds good to me, I vote for 88

**Comment by OriolAbril** [comment]
Did most of the updates mentioned in #9, I'll close the issue, but we can reopen and revisit any of these at any time
